name: Deploy Read Microservice to AWS EC2

on:
  push:
    branches:
      - main
    paths:
      - 'read/**'

jobs:
  deploy-read:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/read-service ./read

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/read-service

      - name: SSH into EC2 and deploy container
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_READ_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            docker stop read-service || true
            docker rm read-service || true
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/read-service
            docker run -d --name read-service -p 80:8000 \
              -e DB_HOST=${{ secrets.DB_HOST }} \
              -e DB_NAME=${{ secrets.DB_NAME }} \
              -e DB_USER=${{ secrets.DB_USER }} \
              -e DB_PASS=${{ secrets.DB_PASS }} \
              ${{ secrets.DOCKERHUB_USERNAME }}/read-service
