name: Deploy Read Microservice to AWS EC2 with SSM

on:
  push:
    branches:
      - main
    paths:
      - 'read/**'

jobs:
  deploy-read:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/read-service ./read

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/read-service

      - name: Run SSM Command on EC2
        uses: aws-actions/amazon-ssm-run-command@v1
        with:
          instance-ids: ${{ secrets.EC2_INSTANCE_ID }}
          commands: |
            docker stop read-service || true
            docker rm read-service || true
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/read-service
            docker run -d --name read-service -p 80:8000 \
              -e DB_HOST=${{ secrets.DB_HOST }} \
              -e DB_NAME=${{ secrets.DB_NAME }} \
              -e DB_USER=${{ secrets.DB_USER }} \
              -e DB_PASS=${{ secrets.DB_PASS }} \
              ${{ secrets.DOCKERHUB_USERNAME }}/read-service